name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Run tests
      run: make tests
    - name: Build Docker WMConsole Image and Publish to Github Packages
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ secrets.GIT_USERNAME }}
        password: ${{ secrets.GIT_TOKEN }}
        registry: docker.pkg.github.com
        image_name: witnessme
    - name: Build Docker WMAPI Image and Publish to Github Packages
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ secrets.GIT_USERNAME }}
        password: ${{ secrets.GIT_TOKEN }}
        dockerfile: dockerfiles/Dockerfile.selfhosted
        registry: docker.pkg.github.com
        image_name: witnessme
        image_tag: api
